export const newArrivals = [
  {
    img: "",
    title: "T-shirt with tape details",
    ratings: 4.5,
    price: 120,
    discount: 0,
  },
  {
    img: "",
    title: "T-shirt with tape details",
    ratings: 3.5,
    price: 120,
    discount: 20,
  },
  {
    img: "",
    title: "T-shirt with tape details",
    ratings: 4.5,
    price: 120,
    discount: 0,
  },
  {
    img: "",
    title: "T-shirt with tape details",
    ratings: 4.5,
    price: 120,
    discount: 30,
  },
];

export const topSelling = [
  {
    img: "",
    title: "Vertical Striped Shirt",
    ratings: 5,
    price: 212,
    discount: 20,
  },
  {
    img: "",
    title: "Courage Graphic T-shirt",
    ratings: 4,
    price: 145,
    discount: 0,
  },
  {
    img: "",
    title: "Loose Fit Bermuda Shorts",
    ratings: 3,
    price: 0,
    discount: 0,
  },
  {
    img: "",
    title: "Faded Skinny Jeans",
    ratings: 4.5,
    price: 210,
    discount: 0,
  },
  {
    img: "",
    title: "Vertical Striped Shirt",
    ratings: 5,
    price: 212,
    discount: 20,
  },
  {
    img: "",
    title: "Courage Graphic T-shirt",
    ratings: 4,
    price: 145,
    discount: 0,
  },
  {
    img: "",
    title: "Loose Fit Bermuda Shorts",
    ratings: 3,
    price: 0,
    discount: 0,
  },
  {
    img: "",
    title: "Faded Skinny Jeans",
    ratings: 4.5,
    price: 210,
    discount: 0,
  },
  {
    img: "",
    title: "Faded Skinny Jeans",
    ratings: 4.5,
    price: 210,
    discount: 0,
  },
];
